include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style
    - avoid_print
    - prefer_const_constructors
    - lines_longer_than_80_chars
    - prefer_single_quotes
    - unawaited_futures
    - always_declare_return_types
    - prefer_final_locals
    - sort_child_properties_last
    - sort_constructors_first

    # Security & Best Practices
    - secure_pubspec_urls
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks

    # Code Quality
    - avoid_unnecessary_containers
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_duplicate_case_values
    - valid_regexps

    # Naming
    - camel_case_types
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - file_names
    - package_names

    # Imports
    - directives_ordering
